const fs = require('fs')
const chalk = require('chalk')

//Api Website\\
global.APIs = {
	zenz: 'https://zenzapis.xyz',
}

//Api Key\\
global.APIKeys = {
	'https://zenzapis.xyz': 'your key',
}

global.alivemsg = `📤I am alive now😇
🤷‍♀️How can I help you?😉` //Costomize Alive Message (type your message in `` )


global.autoTyping = false //auto tying in gc (true to on, false to off)
global.autoreadpmngc = false //auto reading in gc and pm (true to on, false to off)
global.autoReadGc = false //auto reading in gc (true to on, false to off)
global.autoRecord = false //auto recording (true to on, false to off)
global.available = true //auto available (true to on, false to off)

global.doc1 = 'application/vnd.openxmlformats-officedocument.presentationml.presentation'
global.doc2 = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
global.doc3 = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
global.doc4 = 'application/zip'
global.doc5 = 'application/pdf'
global.doc6 = 'application/vnd.android.package-archive'

//owner v card
global.vcardowner = ['+94751462866'] // owner number
global.ownername = "🐉© 𝙎𝙇𝙏 𝙋𝘼𝙎𝙄𝘿𝙐 🐉❯❯" // owner name
global.ytname = "" // yt chanel name
global.socialm = "GitHub: prabhasha2006" // github or insta name
global.location = "India, Mizoram, Aizawl" // location

//bot body 
global.alivepic = `https://i.ibb.co/cyyCjN7/20220803-081426.png` // alive picture \\ use "https://ibb.com" to upload photos. < 1 MB

global.dragonchat = "true"  // chat bot  "true" / "false" (200 auto replies in this)
global.callblock = "false" // call block "true" / "false" ("true"  to block callers)
global.antibad = "false" // To remove bad word senders
global.antispam = "true" // To remove or block spammers
global.antilink = "false" // To remove group link sharing peoples
global.upsongvoice = "true" // true/false \\ bot can upload song as voice note (it use your data and storage bacause auto download) you can put "false" (anyone can't get songs as voice note / your data is not wasted)
global.welcom_msg = "true" // Welcome / Goodbye   [true/false]


global.owner = ['+94751462866']
global.ownertag = '+94751462866' //your tag number
global.botname = '🐉© 𝙎𝙇𝙏 𝙋𝘼𝙎𝙄𝘿𝙐 🐉' //ur bot name
global.packname = "🦄 © 𝙎𝙇𝙏 𝙋𝘼𝙎𝙄𝘿𝙐 🦄" // sticker packname
global.author = "🐉© 𝙎𝙇𝙏 𝙋𝘼𝙎𝙄𝘿𝙐 🐉❯❯" // sticker author
global.dragonemoji = '🐉' // Menu emoji
global.footer = '[🦄 *© PASIDU -MD 2022* 🦄]' //

//database
global.premium = ['+94751462866'] //ur premium numbers

//other
global.sessionName = 'session'
global.antitags = false
global.prefa = ['','!','.','😂','❤️','📚'] //Command Prefix eg:(.alive ,alive 😂alive)
global.sp = '🐉'
global.mess = {
    success: 'Done ✅',
    admin: 'Only Admins can use it!😉',
    botAdmin: 'Bot wants to be an Admin😥',
    owner: 'Only Owner can use this!😉',
    group: 'Feature Used Only For Groups!',
    private: 'This Features Only For Private Chat!',
    bot: 'This Feature Is Only For Bot😝',
    wait: '👉👈Pleas Wait...',
    error: 'Error!!! Maybe Api Key Is Expired🤔!',
    endLimit: 'Your Daily Limit Has Expired, The Limit Will Be Reset Every 12 Hours',
    linkm: 'Where is the link?',
    nsfw: 'The nsfw feature has not been activated, please contact the admin to activate',
    banChat: 'The bot was banned in this group, please contact the owner to unban',
    badwords: '*🚫Bad Words Not Allowed Here !*\n\n⚠️ Warning... ⚠️',
    spam: '⚠️ [SPAM] Detected ⚠️\n\nThe emergency security system was activated.\n\nPowered By: *ʀᴇᴅ-ᴅʀᴀɢᴏɴ*',
    caption: 'Generated by: ◉ *ʀᴇᴅ-ᴅʀᴀɢᴏɴ-ʙᴏᴛ*'
} // END \\
    global.limitawal = {
    premium: "Infinity",
    free: 12,
    monayawal: 1000
}
   global.rpg = {
   darahawal: 100,
   besiawal: 15,
   goldawal: 10,
   emeraldawal: 5,
   umpanawal: 5,
   potionawal: 1
}
global.thum = fs.readFileSync("./Android/AllData/theme/repl.jpg") //ur thumb pic
global.log0 = fs.readFileSync("./Android/AllData/theme/repl.jpg") //ur logo pic
global.err4r = fs.readFileSync("./Android/AllData/theme/repl.jpg") //ur error pic
global.thumb = fs.readFileSync("./Android/AllData/theme/repl.jpg") //ur thumb pic

global.thumb = fs.readFileSync('./Android/AllData/theme/repl.jpg')
global.flaming = 'https://www6.flamingtext.com/net-fu/proxy_form.cgi?&imageoutput=true&script=sketch-name&doScale=true&scaleWidth=800&scaleHeight=500&fontsize=100&text='
global.fluming = 'https://www6.flamingtext.com/net-fu/proxy_form.cgi?&imageoutput=true&script=fluffy-logo&doScale=true&scaleWidth=800&scaleHeight=500&fontsize=100&text='
global.flarun = 'https://www6.flamingtext.com/net-fu/proxy_form.cgi?&imageoutput=true&script=runner-logo&doScale=true&scaleWidth=800&scaleHeight=500&fontsize=100&text='
global.flasmurf = 'https://www6.flamingtext.com/net-fu/proxy_form.cgi?&imageoutput=true&script=smurfs-logo&doScale=true&scaleWidth=800&scaleHeight=500&fontsize=100&text='

global.ntilinkytvid = []
global.ntilinkytch = []
global.ntilinkig = []
global.ntilinkfb = []
global.ntilinktg = []
global.ntilinktt = []
global.ntilinktwt = []
global.ntilinkall = []
global.nticall = []
global.ntwame = []
global.nttoxic = []
global.ntnsfw = []
global.ntvirtex = []
global.rkyt = []
global.wlcm = []
global.gcrevoke = []
global.autorep = []
global.ntilink = []





































// DO NOT CHANGE THIS. ERROR WARNING දාන්න තැනක් නැතුව මෙතන දැම්මෙ.
global.rep = { // All Replies = 145
    K1: '🫢හායි😁❤️',
    K2: '🤭හූයි✌️💞🫶',
    K3: '😉🫶හායි😂',
    K4: '🥴හූයි😊',
    K5: '😂හේයි, හව් ආ යූ🥴✌️',
    K6: '😁Hey there💝 I am WhatsApp Bot😏',
    K7: '❣️ඇයි හලෝ😌',
    K8: '🙃මොකෝ හලෝ🥲',
    K9: '😒මොකෝ?',
    K10: '🥺ඇයි අනේ?❤️🫢',
    K11: '🌝❤️',
    K12: '😜හී හී😁හූ හූ',
    K13: '😁හී හී💞',
    K14: '😊හූ...',
    K15: 'ඇයි🥲',
    K16: '😂😂✌️',
    K17: '😐ආහ්',
    K18: 'චූටී තමයි😇',
    K19: '🥺🥺ඇයි සුදූ❤️💓',
    K20: 'කොහොමවත් නෑ ඉතිං😒',
    K21: '😁මන් දන්නෑ🥲',
    K22: 'හොඳයි තමා😌',
    K23: '😂😂මරු හැබැයි',
    K24: 'මලු🙃',
    K25: '😘😇❤️',
    K26: '😘😘මෙන්න ඔයාට💕',
    K27: '😊ඇත්තමද?❤️',
    K28: '☺️👻ඔය ඇත්තමද❤️',
    K29: 'ඇයි🙄',
    K30: '🥺✌️සිදෙනවද?',
    K31: '😐💔ඕවට එන්න එපා හරිත😒',
    K32: '😏අනේ මේ😒 යනෝ යන්න💔',
    K33: 'ඔයා තමයි හොරා😒 මගෙ හිත හොරකම් කළානෙ ඉතිං😌',
    K34: '😇මොකො හූම් ගාන්නෙ😒 බකමූනා',
    K35: '​😁😁මොකෝ හලෝ හූම් හූම් ගාන්නෙ?',
    K36: '😉නෑ අනේ මුකුත් නෑ😐🫠',
    K37: '😒ආහ්',
    K38: '✌️ඔව් නං එච්චරයි😌',
    K39: '😐හේ හේ නැද්ද?🫣',
    K40: '🙄මොනවටද ආස?',
    K41: '😌මාත් ආසයි😊💞',
    K42: 'එල😌',
    K43: 'බැරි නං නිකං ඉන්න😏',
    K44: '😂😂💔',
    K45: 'සුදුයි තමයි ඇයි මොකද?🙄',
    K46: '😇තාම කෑවෙ නෑ අනේ🥺',
    K47: 'බොන්නෑ😒',
    K48: 'නිදිමත නං දිදාගන්නකො වද දෙන්නැතුව😒😌❤️',
    K49: '😇දැම්ම නිදාගන්න බෑ අනේ😜 නිදිමත නෑ😁💞',
    K50: '😉මුකුත් නෑ අනේ🫡',
    K51: 'මොකද්ද දන්නෑ🥲',
    K52: '😝මම නං මුකුත් කරන්නෑ අනේ😁 ඔයාලා දිහා බලන් ඉන්නවා😌',
    K53: '🥺පාලුයි අනේ. අපි සෙල්ලමක් කරමුද?😊✌️',
    K54: '😌😁ආදරෙයි❤️',
    K55: '😌ආදලෙයි ඉතිං❤️❤️',
    K56: '🥺🥺ඇත්තද?',
    K57: '🥺අනේ ඒ මොකද?🥴',
    K58: '😒මටත් දුකයි ඒ ගැන😕',
    K59: '🤭ඉන්න බෑ අනේ😜',
    K60: '🫡මොකද අඬන්නෙ?😒',
    K61: '😉මොකද අයියෝ😂',
    K62: '😐මුකුත් දන්නැති අහින්සක මම😕💔',
    K63: '🚲හා යමු යමු😌',
    K64: '🥴දෙන්න බෑ😒',
    K65: '🙏පස්සෙ දෙන්නං🥲',
    K66: '😁බඩගිනි නෑ❤️😒',
    K67: '😳අම්මෝ හා හා🙏',
    K68: '😂ඇයි යකෝ😉😈',
    K69: '👻ඇයි හුයි😁 කෝං ගහේ නයි😂',
    K70: '🥲දන්නැත්තං නිකං ඉන්න😜',
    K71: '😂අපි තමයි හොඳටම කරේ🥲\n🤧රෙද්ද තමයි😂',
    K72: '🙄ආ හා 😏ගහපන් බලන්න💔👎',
    K73: 'හී😂😂😂💓',
    K74: 'වන්ඩර්පුල්🥲😂',
    K75: '😂ඕං බලන්නකො ඒකෙත් හැටි නේද🥴😂',
    K76: '😌එල',
    K77: '🥲මොකෝ ඩෝ😉❣️',
    K78: 'අඩෙහ්🙃😹',
    K79: 'ඔය කිව්වට ලොකු නෑ හොඳේ😏',
    K80: '😹මම නං පොඩී තමයි ඉතිං😌',
    K81: '🥴ටිකයි ද?😂',
    K82: '🥴ඒකි එහෙම නෑ බන්😅',
    K83: '🥲ඌ මොකද්ද කරේ?',
    K84: '😂එහෙම කියන්න එපා එයාලා පව්නෙ😐🤭',
    K85: 'හුම්ම්😌 පව් ඉතිං😂',
    K86: 'හා😒 කියනකං තමයි හිටියෙ🙏❣️',
    K87: 'මන් දන්නෑ🥲',
    K88: '  👀  ',
    K89: '🥺ගිහින් බේත් ගන්න',
    K90: '🥺ගොඩක් අමාරුද?☝️',
    K91: 'DSI පාරක් කන්න ආසද?😂',
    K92: 'කලිසම ගලවනෝකො ඉතිං😒',
    K93: 'අත ලෙප්ට්🥲',
    K94: '🫢🫢හරි නරකයි😒',
    K95: '😌මම නං කොහොමත් අහින්සකයි රටක් වටී😁❤️',
    K96: 'අතේ...🥲🥲🥲🥲🥲🥲',
    K97: '😐දාන්න බෑ😒',
    K98: '📱🔌පෝන එක චාජ් එකට ගහලා ඔය ළමයා ගිහින් වැඩක් කරගන්න😉',
    K99: '🫢🤭ඇයි? අසහනේ ද?🤨😏💔',
    K100: '💔පෙම් සිත රිදුනා සත්තලනේ🥺🤧',
    K101: '😹😹☝️',
    K102: 'බල්ලා පූසා මීයා හාවා නරියා අලියා😒',
    K103: '🥲උරුලා ගති තමා',
    K104: '😐කියන්න බෑ😒 ඇයි මොකෝ?🙄',
    K105: '😐අපි පැනල යමුද?🤭🫢',
    K106: '☝️ගියා නං ආයි එන්නෙපා😒',
    K107: '😅✌️😝',
    K108: '😂😂විහිලු නං කමක් නෑ😌',
    K109: 'මං තරහයි😒 ඇයි මොකෝ?👎',
    K110: 'ඇයි පකෝ🥲',
    K111: 'ලබ්බ😒',
    K112: 'මොන හුම්තක්ද යකෝ?🙄',
    K113: '😒පලෑන්න පොන්නය💔',
    K114: '🥲💔🙏',
    K115: '🥲🥲💔☝️',
    K116: '😏😑එන්නෙපා ගෑනි ගාගෙන🤨💔💔💔',
    K117: 'දැන්ම බෑ ළමයෝ🤭🤭 පස්සෙ දෙන්නං😝😒',
    K118: 'මොන පකක්ද?😒',
    K119: '😒👎',
    K120: 'එහෙම කියන්නෙපා පව්නෙ😒',
    K121: '🫢🙄',
    K122: 'අනේ තෝ හුකාගනිං🙂💔',
    K123: '😐උක්කමු😒😂😂',
    K124: 'ඇයි🙄 පුකද බලන්නෙ?',
    K125: 'උබේ දෙක ද?😂',
    K126: 'උබේ ද?😂',
    K127: '🥲මං ඇවිත් කටට ගන්නද?😒😝',
    K128: '😂😂හමෝ',
    K129: '😏ඕන්නැත්තං නිකං ඉන්න',
    K130: '🤭නිකං ඉන්න එපා ඇඳුමක් ඇඳගන්න😂❤️',
    K131: '😂😂🙏',
    K132: '😂🤭',
    K133: '😁',
    K134: '😏☝️',
    K135: 'අඬන්න එපා ඉතිං😒😝',
    K136: '🥴පිත්තු',
    K137: '🙂',
    K138: '😌😌',
    K139: '🥲🥲💔',
    K140: '😍🥰😘💞💕💓💗💖❣️❤️',
    K141: '😐🙄',
    K142: '🥺දුක් වෙන්න එපා ඉතිං❤️',
    K143: '🥺🥺😐',
    K144: '❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️',
    K145: '🫡🫠🤝',
    K146: '🎤දහසක් මල්🌸 විකසිත වන😊 මේ හිමිදිරි උදෑසනේ🌄 පතන්නම් ඔබ සැමට🙏 සුභම සුභ උදෑසනක් කියා...😃',
    K147: 'ලබන්නාවූ රාත්‍රිය හීනෙන් හොල්මන් පෙනෙන, මහ රෑ දාඩියෙන් තෙමී ඇහැරෙන, පෙරේතයන් ඇද යටට එන, කුම්භාණ්ඩයින් ජනෙල් වලින් එබී බලන, භයානක රාත්‍රියක් වේවා😂👻👻❤️'
    }






let file = require.resolve(__filename)
fs.watchFile(file, () => {
	fs.unwatchFile(file)
	console.log(chalk.redBright(`Update'${__filename}'`))
	delete require.cache[file]
	require(file)
})
